#!/usr/bin/env bash
# Create the file /var/run/holbertonscript.pid containing its PID, Displays To infinity and beyond indefinitely, Displays I hate the kill command when receiving a SIGTERM signal, Displays Y U no love me?! when receiving a SIGINT signal, Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

pgrep -f 100-process_and_pid_file > /var/run/myscript.pid
trap "echo Y U no love me?!" SIGINT
trap "echo I hate the kill command; rm -f /var/run/holbertonscript.pid; exit" SIGTERM SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done