#!/usr/bin/env bash
# Prints on the 9th iteration 'Hi'

i='1'

while [ $i -ne 10 ]; do
      echo "Best School"

      if [ $i = 9 ]; then
          echo "Hi"
	  echo "Best School"
      fi

      ((i++))
done
