#!/usr/bin/env bash
# Prints the hours of the clock

hour="0"
minutes="1"

while [ $hour -le 12 ]; do

      echo "Hour: $hour"
      ((minutes = 1))

      while [ $minutes -le 59 ]; do

      	    echo $minutes
      	    ((minute++))
      done

      ((hour++))
done
