#!/usr/bin/env bash
# Set a shell for a desired user
# and execute the "whoami" command
#

if [ "$#" -eq 1 ]; then
    user="$1"
    chsh -s "$(which bash)" "$user" && su "$user" -c "whoami"
else
    echo "Usage: $0 <username>"
fi
